language: cpp

compiler:
  - gcc

before_script:
  - sudo sh -c 'echo "deb http://www.icub.org/ubuntu precise contrib/science" > /etc/apt/sources.list.d/icub.list'
  - sudo sh -c 'echo "deb http://packages.osrfoundation.org/gazebo/ubuntu precise main" > /etc/apt/sources.list.d/gazebo-latest.list'
  - wget http://packages.osrfoundation.org/gazebo.key -O - | sudo apt-key add -
  - sudo apt-get update 
  - sudo apt-get --force-yes install icub libtinyxml-dev gazebo
  - mkdir build
  - cd build
  - cmake ./..

script: make 
